import { Command, CommandStatus } from '@/types/command';
import { Folder } from '@/types/folder';

export const DUMMY_COMMANDS: Command[] = [
  {
    id: 'cmd-1',
    name: 'Build Project',
    description: 'Build the entire project with optimizations',
    script: 'npm run build',
    folder_path: '/',
    status: CommandStatus.IDLE,
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2024-01-01'),
    execution_count: 5,
    last_executed: new Date('2024-01-15'),
    tags: ['build', 'npm'],
  },
  {
    id: 'cmd-2',
    name: 'Start Dev Server',
    description: 'Start the development server with hot reload',
    script: 'npm run dev',
    folder_path: '/',
    status: CommandStatus.IDLE,
    created_at: new Date('2024-01-01'),
    updated_at: new Date('2024-01-01'),
    execution_count: 12,
    last_executed: new Date('2024-01-20'),
    tags: ['dev', 'server'],
  },
  {
    id: 'cmd-3',
    name: 'Run Tests',
    description: 'Execute all test suites',
    script: 'npm test',
    folder_path: '/testing',
    status: CommandStatus.SUCCESS,
    created_at: new Date('2024-01-02'),
    updated_at: new Date('2024-01-02'),
    execution_count: 8,
    last_executed: new Date('2024-01-18'),
    tags: ['test', 'quality'],
  },
  {
    id: 'cmd-4',
    name: 'Deploy to Staging',
    description: 'Deploy application to staging environment',
    script: 'npm run deploy:staging',
    folder_path: '/deployment',
    status: CommandStatus.FAILED,
    created_at: new Date('2024-01-03'),
    updated_at: new Date('2024-01-03'),
    execution_count: 3,
    last_executed: new Date('2024-01-19'),
    tags: ['deploy', 'staging'],
  },
  {
    id: 'cmd-5',
    name: 'Database Migration',
    description: 'Run pending database migrations',
    script: 'npm run db:migrate',
    folder_path: '/database',
    status: CommandStatus.RUNNING,
    created_at: new Date('2024-01-04'),
    updated_at: new Date('2024-01-04'),
    execution_count: 2,
    last_executed: new Date(),
    tags: ['database', 'migration'],
  },
];

export const DUMMY_FOLDERS: Folder[] = [
  {
    path: '/',
    name: 'Root',
    created_at: new Date('2024-01-01'),
  },
  {
    path: '/testing',
    name: 'Testing',
    parent_path: '/',
    created_at: new Date('2024-01-01'),
  },
  {
    path: '/deployment',
    name: 'Deployment',
    parent_path: '/',
    created_at: new Date('2024-01-01'),
  },
  {
    path: '/database',
    name: 'Database',
    parent_path: '/',
    created_at: new Date('2024-01-01'),
  },
];