name: ordito
base: core22
version: "1.1.0"
summary: A powerful desktop application for organizing and executing commands
description: |
  A powerful desktop application for organizing and executing commands from a convenient system tray interface.
  Ordito lets you create, manage, and run groups of shell commands directly from your system tray, streamlining your workflow
  and automating repetitive tasks.

grade: stable
confinement: strict

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

apps:
  ordito:
    command: usr/bin/ordito
    desktop: usr/share/applications/ordito.desktop
    extensions: [gnome]
    # If you need extra plugs:
    # plugs:
    #   - network
    #   - home
    #   - x11
    #   - wayland
    # The gnome extension already grants [desktop, desktop-legacy, gsettings, opengl, wayland, x11, mount-observe, calendar-service].

parts:
  build-app:
    plugin: dump
    # We no longer declare build-snaps (node/20 or rustup). Instead, assume CI has Node, pnpm, Rust, etc.
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    source: .
    override-build: |
      set -eux

      # Install pnpm (already installed on runner via GitHub Actions)
      # But just in case: make sure pnpm exists
      command -v pnpm >/dev/null 2>&1 || npm install -g pnpm

      # 1) Install your frontend & Tauri dependencies
      pnpm install

      # 2) Build your Tauri app into a .deb bundle
      pnpm tauri build -- --bundles deb

      # 3) Extract the .deb into the Snap’s filesystem
      dpkg -x src-tauri/target/release/bundle/deb/*.deb $SNAPCRAFT_PART_INSTALL/

      # 4) Correct the Icon path inside the desktop file
      sed -i -e "s|Icon=ordito|Icon=/usr/share/icons/hicolor/32x32/apps/ordito.png|g" \
        $SNAPCRAFT_PART_INSTALL/usr/share/applications/ordito.desktop
