name: ordito
base: core22
version: "1.1.0"
summary: Dummy
description: |
  A powerful desktop application for organizing and executing commands from a convenient system tray interface.
  Ordito lets you create, manage, and run groups of shell commands directly from your system tray, streamlining your workflow
  and automating repetitive tasks.

grade: stable
confinement: strict

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

apps:
  ordito:
    command: usr/bin/ordito
    desktop: usr/share/applications/ordito.desktop
    extensions: [gnome]
    # Uncomment and add any plugs you need:
    # plugs:
    #   - network
    #   - home
    #   - desktop
    #   - x11
    #   - wayland
    # The gnome extension already includes [desktop, desktop-legacy, gsettings, opengl, wayland, x11, mount-observe, calendar-service]

parts:
  build-app:
    plugin: dump
    build-snaps:
      - node/20/stable
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    source: .
    override-build: |
      set -eux
      # Install Node.js dependencies
      npm install
      # Build the Tauri app and package as a .deb bundle
      npm run tauri build -- --bundles deb
      # Extract the .deb into the snap filesystem
      dpkg -x src-tauri/target/release/bundle/deb/*.deb $SNAPCRAFT_PART_INSTALL/
      # Fix the desktop file's Icon entry to point inside the snap
      sed -i -e "s|Icon=ordito|Icon=/usr/share/icons/hicolor/32x32/apps/ordito.png|g" $SNAPCRAFT_PART_INSTALL/usr/share/applications/ordito.desktop
