name: ordito
base: core22
version: "1.1.0"
summary: A powerful desktop app for organizing and executing commands from the tray.
description: |
  Ordito helps you organize command groups and execute them from the system tray. Ideal for developers, sysadmins, and power users.

grade: stable
confinement: strict

parts:
  ordito:
    plugin: rust
    source: .
    override-build: |
      # Install frontend deps and build
      npm install -g pnpm
      pnpm install
      pnpm build

      # Build the tauri app
      cargo build --release

      # Move binary to expected location
      install -Dm755 target/release/ordito $SNAPCRAFT_PART_INSTALL/usr/bin/ordito

      # Copy frontend assets if needed
    build-packages:
      - curl
      - libgtk-3-dev
      - libayatana-appindicator3-dev
      - libsoup2.4-dev
      - libwebkit2gtk-4.0-dev
      - build-essential
      - pkg-config
      - libssl-dev
      - nodejs
      - npm
      - libglib2.0-dev
      - ca-certificates

apps:
  ordito:
    command: usr/bin/ordito
    extensions: [gnome]
    plugs:
      - network
      - home
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - unity7
      - pulseaudio
      - browser-support
