import type { LucideIcon } from "lucide-react";
import {
  Box,
  Boxes,
  Bug,
  Calendar,
  CalendarClock,
  CircleCheck,
  CirclePlay,
  CircleX,
  Clock,
  Cloud,
  Code,
  Container,
  Cpu,
  Database,
  Download,
  Folder,
  FolderGit2,
  FolderOpen,
  GitBranch,
  GitCommitHorizontal,
  GitMerge,
  GitPullRequest,
  Globe,
  HardDrive,
  Info,
  Key,
  Layers,
  Link2,
  Lock,
  Network,
  Package,
  PackageOpen,
  Play,
  Power,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Rocket,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  SquareTerminal,
  Terminal,
  TriangleAlert,
  Upload,
  Webhook,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";

export type LucideIconEntry = {
  name: string;
  icon: LucideIcon;
};

export const lucideIconList: LucideIconEntry[] = [
  { name: "terminal", icon: Terminal },
  { name: "square-terminal", icon: SquareTerminal },
  { name: "play", icon: Play },
  { name: "circle-play", icon: CirclePlay },
  { name: "refresh-cw", icon: RefreshCw },
  { name: "refresh-ccw", icon: RefreshCcw },
  { name: "repeat", icon: Repeat },
  { name: "power", icon: Power },
  { name: "database", icon: Database },
  { name: "server", icon: Server },
  { name: "hard-drive", icon: HardDrive },
  { name: "cpu", icon: Cpu },
  { name: "network", icon: Network },
  { name: "cloud", icon: Cloud },
  { name: "globe", icon: Globe },
  { name: "webhook", icon: Webhook },
  { name: "link", icon: Link2 },
  { name: "download", icon: Download },
  { name: "upload", icon: Upload },
  { name: "git-branch", icon: GitBranch },
  { name: "git-merge", icon: GitMerge },
  { name: "git-pull-request", icon: GitPullRequest },
  { name: "git-commit", icon: GitCommitHorizontal },
  { name: "folder-git", icon: FolderGit2 },
  { name: "folder", icon: Folder },
  { name: "folder-open", icon: FolderOpen },
  { name: "package", icon: Package },
  { name: "package-open", icon: PackageOpen },
  { name: "box", icon: Box },
  { name: "boxes", icon: Boxes },
  { name: "container", icon: Container },
  { name: "layers", icon: Layers },
  { name: "workflow", icon: Workflow },
  { name: "code", icon: Code },
  { name: "bug", icon: Bug },
  { name: "wrench", icon: Wrench },
  { name: "settings", icon: Settings },
  { name: "shield", icon: Shield },
  { name: "shield-check", icon: ShieldCheck },
  { name: "lock", icon: Lock },
  { name: "key", icon: Key },
  { name: "clock", icon: Clock },
  { name: "calendar", icon: Calendar },
  { name: "calendar-clock", icon: CalendarClock },
  { name: "rocket", icon: Rocket },
  { name: "zap", icon: Zap },
  { name: "alert-triangle", icon: TriangleAlert },
  { name: "check-circle", icon: CircleCheck },
  { name: "x-circle", icon: CircleX },
  { name: "info", icon: Info },
];
