/**
 * GENERATED BY scripts/sync-brand.mjs — DO NOT EDIT BY HAND.
 * Source of truth: brand.json at the repo root. Run `pnpm sync-brand`.
 */

export const scriptUrls = {
  "setupSh": "https://raw.githubusercontent.com/tonmoydeb404/ordito/main/setup.sh",
  "setupPs1": "https://raw.githubusercontent.com/tonmoydeb404/ordito/main/setup.ps1"
} as const;
