name: Build Snap

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tauri CLI
        run: pnpm dlx @tauri-apps/cli install

      - name: Build Snap
        uses: snapcore/action-build@v1
        with:
          snapcraft-args: "--destructive-mode"
