# .github/workflows/build-snap.yml
name: Build Snap Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-snap:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node + pnpm setup
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      # Rust
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      # Install system libraries
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            libwebkit2gtk-4.1-dev \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            curl \
            wget \
            file \
            dpkg \
            snapd

      # Install Snapcraft without LXD
      - name: Install Snapcraft (Classic)
        run: |
          samuelmeuli/action-snapcraft@v3

      - name: Build Snap (no LXD)
        run: |
          snapcraft

      # Upload the Snap
      - name: Upload Snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: ordito-snap
          path: ./*.snap
