name: Build Snap Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-snap:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            libwebkit2gtk-4.1-dev \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            curl \
            wget \
            file \
            dpkg

      - name: Install Snapcraft
        uses: snapcore/action-build@v1
        with:
          snapcraft-args: "--destructive-mode"

      - name: Upload Snap Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ordito-snap
          path: ./*.snap
