name: Build Ordito Snap

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-snap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm@10.11.0

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Install dependencies
        run: pnpm install

      - name: Build frontend (Vite) and Tauri binary
        run: |
          pnpm build
          pnpm tauri build

      - name: Install Snapcraft
        run: |
          sudo snap install snapcraft --classic
          snapcraft --version

      - name: Build Snap package
        run: |
          snapcraft --use-lxd --destructive-mode

      - name: Upload .snap artifact
        uses: actions/upload-artifact@v3
        with:
          name: ordito-snap
          path: "*.snap"
