# .github/actions/generate-updater/action.yml
name: "Generate Updater JSON"
description: "Generate updater JSON file and publish release"

inputs:
  tag:
    description: "Git tag to generate updater for"
    required: true
  github_token:
    description: "GitHub token for release access"
    required: true
  release_notes:
    description: "Custom release notes"
    required: false
    default: ""
  repository:
    description: "GitHub repository (owner/repo)"
    required: true

outputs:
  updater_url:
    description: "URL to the updater JSON file"
    value: ${{ steps.publish.outputs.updater_url }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Get release info
      id: release_info
      shell: bash
      run: |
        TAG="${{ inputs.tag }}"
        RELEASE_TAG="$TAG"
        VERSION=${TAG#v}
        PUB_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "pub_date=$PUB_DATE" >> $GITHUB_OUTPUT

        echo "Processing:"
        echo "  Original tag: $TAG"
        echo "  Release tag: $RELEASE_TAG"
        echo "  Version: $VERSION"
        echo "  Date: $PUB_DATE"

    - name: Download release assets
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        echo "📥 Downloading assets for release: ${{ steps.release_info.outputs.release_tag }}"
        echo "Repository: ${{ inputs.repository }}"
        echo "Looking for release at: https://github.com/${{ inputs.repository }}/releases/tag/${{ steps.release_info.outputs.release_tag }}"

        echo "🔍 Getting all releases and finding target..."

        # Get all releases and find our target release
        ALL_RELEASES=$(gh api repos/${{ inputs.repository }}/releases)

        # Find the specific release by tag
        RELEASE_DATA=$(echo "$ALL_RELEASES" | jq -r ".[] | select(.tag_name == \"${{ steps.release_info.outputs.release_tag }}\")")

        if [ -z "$RELEASE_DATA" ] || [ "$RELEASE_DATA" = "null" ]; then
          echo "❌ Release not found: ${{ steps.release_info.outputs.release_tag }}"
          echo ""
          echo "🔍 Available releases:"
          echo "$ALL_RELEASES" | jq -r '.[] | "- \(.tag_name) (\(.name)) [draft: \(.draft)]"' | head -10
          exit 1
        fi

        # Extract release info
        RELEASE_ID=$(echo "$RELEASE_DATA" | jq -r '.id')
        IS_DRAFT=$(echo "$RELEASE_DATA" | jq -r '.draft')
        RELEASE_NAME=$(echo "$RELEASE_DATA" | jq -r '.name')

        echo "✅ Release found!"
        echo "   ID: $RELEASE_ID"
        echo "   Name: $RELEASE_NAME"
        echo "   Draft: $IS_DRAFT"

        if [ "$RELEASE_ID" = "null" ] || [ -z "$RELEASE_ID" ]; then
          echo "❌ Release not found: ${{ steps.release_info.outputs.release_tag }}"
          exit 1
        fi

        echo "Release ID: $RELEASE_ID"

        # Create assets directory
        mkdir -p assets

        # Download all release assets
        ASSETS=$(gh api repos/${{ inputs.repository }}/releases/$RELEASE_ID/assets)
        ASSET_COUNT=$(echo "$ASSETS" | jq length)

        echo "Found $ASSET_COUNT asset(s) to download"

        if [ "$ASSET_COUNT" = "0" ]; then
          echo "❌ No assets found in release"
          exit 1
        fi

        # Download assets using GitHub API (works with draft releases)
        echo "$ASSETS" | jq -r '.[] | select(.name | test("\\.(AppImage|AppImage\\.sig|msi|msi\\.sig|exe|exe\\.sig|app\\.tar\\.gz|app\\.tar\\.gz\\.sig)$")) | .url' | while read asset_url; do
          # Get asset info
          ASSET_INFO=$(echo "$ASSETS" | jq -r ".[] | select(.url == \"$asset_url\")")
          ASSET_NAME=$(echo "$ASSET_INFO" | jq -r '.name')
          
          echo "Downloading: $ASSET_NAME"
          
          # Download using GitHub API (works with draft releases)
          curl -L \
               -H "Authorization: Bearer ${{ inputs.github_token }}" \
               -H "Accept: application/octet-stream" \
               "$asset_url" \
               -o "assets/$ASSET_NAME" \
               --fail --silent --show-error
        done

        echo "Downloaded assets:"
        ls -la assets/

    - name: Generate updater JSON
      shell: bash
      env:
        VERSION: ${{ steps.release_info.outputs.version }}
        TAG_NAME: ${{ steps.release_info.outputs.release_tag }}
        PUB_DATE: ${{ steps.release_info.outputs.pub_date }}
        REPOSITORY: ${{ inputs.repository }}
        RELEASE_NOTES: ${{ inputs.release_notes || format('Release v{0}. Download the appropriate installer for your platform.', steps.release_info.outputs.version) }}
      run: |
        echo "🔧 Generating updater JSON..."

        # Helper function to find asset
        find_asset() {
          local pattern="$1"
          find assets -name "$pattern" -type f | head -1
        }

        # Helper function to generate platform entry
        generate_platform() {
          local platform="$1"
          local file_pattern="$2"
          local sig_pattern="$3"
          
          local main_file=$(find_asset "$file_pattern")
          local sig_file=$(find_asset "$sig_pattern")
          
          if [[ -n "$main_file" && -n "$sig_file" ]]; then
            local signature=$(cat "$sig_file" | tr -d '\n')
            local filename=$(basename "$main_file")
            local download_url="https://github.com/$REPOSITORY/releases/download/$TAG_NAME/$filename"
            
            echo "  ✅ $platform: $filename"
            
            # Add platform to JSON (we'll build this incrementally)
            echo "    \"$platform\": {"
            echo "      \"signature\": \"$signature\","
            echo "      \"url\": \"$download_url\""
            echo "    },"
          else
            echo "  ⏭️  Skipped $platform (missing files)"
            return 1
          fi
        }

        # Start building the JSON
        cat > latest.json << EOF
        {
          "version": "$VERSION",
          "notes": "$RELEASE_NOTES",
          "pub_date": "$PUB_DATE",
          "platforms": {
        EOF

        # Track if we added any platforms
        platforms_added=0

        # Generate platform entries
        echo "📦 Processing platforms..."

        # Linux x86_64
        if generate_platform "linux-x86_64" "*.AppImage" "*.AppImage.sig" >> latest.json; then
          platforms_added=$((platforms_added + 1))
        fi

        # Windows x86_64  
        if generate_platform "windows-x86_64" "*-setup.exe" "*-setup.exe.sig" >> latest.json; then
          platforms_added=$((platforms_added + 1))
        fi

        # Try MSI if no setup.exe found
        if [ $platforms_added -eq 0 ] || ! find assets -name "*-setup.exe" -type f | head -1 > /dev/null; then
          if generate_platform "windows-x86_64" "*.msi" "*.msi.sig" >> latest.json; then
            platforms_added=$((platforms_added + 1))
          fi
        fi

        # macOS x86_64
        if generate_platform "darwin-x86_64" "*_x64.app.tar.gz" "*_x64.app.tar.gz.sig" >> latest.json; then
          platforms_added=$((platforms_added + 1))
        fi

        # macOS aarch64 (Apple Silicon)
        if generate_platform "darwin-aarch64" "*_aarch64.app.tar.gz" "*_aarch64.app.tar.gz.sig" >> latest.json; then
          platforms_added=$((platforms_added + 1))
        fi

        # macOS Universal (fallback)
        if generate_platform "darwin-universal" "*.app.tar.gz" "*.app.tar.gz.sig" >> latest.json; then
          platforms_added=$((platforms_added + 1))
        fi

        # Check if we found any platforms
        if [ $platforms_added -eq 0 ]; then
          echo "❌ No valid platform assets found!"
          echo "Available files:"
          ls -la assets/
          exit 1
        fi

        # Remove the trailing comma from the last platform entry
        sed -i '$ s/,$//' latest.json

        # Close the JSON
        cat >> latest.json << EOF
          }
        }
        EOF

        echo ""
        echo "✅ Generated updater JSON for $platforms_added platform(s)"

    - name: Validate JSON
      shell: bash
      run: |
        echo "🔍 Validating generated JSON..."

        if [ ! -f "latest.json" ]; then
          echo "❌ latest.json not found!"
          exit 1
        fi

        # Validate JSON syntax
        if ! jq empty latest.json 2>/dev/null; then
          echo "❌ Invalid JSON syntax!"
          cat latest.json
          exit 1
        fi

        # Check required fields
        VERSION=$(jq -r '.version // empty' latest.json)
        PLATFORMS_COUNT=$(jq -r '.platforms | length' latest.json)

        if [ -z "$VERSION" ]; then
          echo "❌ Missing version field!"
          exit 1
        fi

        if [ "$PLATFORMS_COUNT" = "0" ]; then
          echo "❌ No platforms found!"
          exit 1
        fi

        echo "✅ JSON validation passed!"
        echo "Version: $VERSION"
        echo "Platforms: $PLATFORMS_COUNT"

        # Show generated JSON
        echo "Generated JSON:"
        jq '.' latest.json

    - name: Upload and publish
      id: publish
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        echo "📤 Uploading latest.json to release..."

        gh release upload ${{ steps.release_info.outputs.release_tag }} latest.json \
          --repo ${{ inputs.repository }} \
          --clobber

        echo "✅ Successfully uploaded updater JSON!"

        echo "📢 Publishing release..."

        gh release edit ${{ steps.release_info.outputs.release_tag }} \
          --repo ${{ inputs.repository }} \
          --draft=false

        UPDATER_URL="https://github.com/${{ inputs.repository }}/releases/latest/download/latest.json"
        echo "updater_url=$UPDATER_URL" >> $GITHUB_OUTPUT

        echo "🎉 Release published with auto-updater support!"
        echo ""
        echo "🔗 Updater endpoint: $UPDATER_URL"
